package ffmpeg

import (
	"fmt"
	"strconv"
	"strings"

	"bjoernblessin.de/go-utils/util/assert"

	"bjoernblessin.de/screenshare/internal/capabilities"
	"bjoernblessin.de/screenshare/internal/gpu"
	"bjoernblessin.de/screenshare/internal/settings"
)

// probeHeavySource and probeLightSource are the lavfi graphs the two ends of the measured range
// are generated by, and the ffmpeg counterpart of the GStreamer engine's two test patterns.
// Both engines therefore answer one question about a machine.
//
// Heavy is uncorrelated noise: nothing predicts from the frame before,
// nothing repeats inside a frame, and an encoder does the most work any content can ask of it.
// Light is ffmpeg's test picture, flat fields with one moving element.
// A screen sits between the two.
//
// The noise runs over a solid colour rather than over a picture,
// so the filter's own cost does not depend on the frame it is laid on.
const (
	probeHeavySource = "color=c=gray:s=%dx%d:r=%d,format=bgr0,noise=alls=100:allf=t+u"
	probeLightSource = "testsrc=size=%dx%d:rate=%d"
)

// BuildEncodeProbeArgs returns the arguments that encode generated frames with this stream's
// encoder and discard the coded bytes,
// timing a machine with no screen to capture and no relay to send to.
// frames is how many are encoded, and the caller times the run.
// heavy picks the end of the content range they
// are generated at (probeHeavySource, probeLightSource).
//
// The encoder half is the publish command's own: same encoder, rate-control arguments,
// pixel format, colour range and keyframe interval.
// Only the two ends differ, a lavfi source for the grabber and the null muxer for the transport.
//
// A surface encoder still uploads, as it does for a run: VAAPI, QSV and Vulkan read GPU surfaces,
// so one timed off system frames would be timed doing nothing it does.
// The GPU capture path is the one piece out of reach,
// where frames sit on the device already and cross no bus.
// A generated frame starts in system memory, so a capture and encoder that share device memory
// are timed with the upload they avoid.
//
// The transport goes unchecked, unlike BuildPublishArgs.
// Refusing a measurement because the codec cannot reach the relay over the configured leg
// would answer a question about this machine with a fact about a protocol.
func BuildEncodeProbeArgs(s settings.Settings, width, height, frames int, heavy bool) ([]string, error) {
	assert.Assert(width > 0 && height > 0, "a probe encodes frames of a resolved picture size", width, height)
	assert.Assert(frames > 0, "a probe encodes at least one frame", frames)

	if err := capabilities.Validate(capabilities.EngineFfmpeg, s.Publish.Codec(), s.Publish.CapabilityOptions(), s.Publish.Cq, s.Publish.BitrateM, s.Publish.Gop, gpu.Device()); err != nil {
		return nil, err
	}
	if s.Publish.Fps <= 0 {
		return nil, fmt.Errorf("the ffmpeg publish engine needs a positive fps, got %d", s.Publish.Fps)
	}

	enc, err := encoderArgs(s, gopFor(s))
	if err != nil {
		return nil, err
	}
	assert.Assert(len(enc) > 0, "a validated stream yields an encoder", s.Publish.Codec())

	device, uploads, err := HwSurfaceDevice(s.Publish.Codec())
	if err != nil {
		return nil, err
	}

	var filters []string
	if colour := colourFilter(s.Publish.Chroma); colour != "" {
		filters = append(filters, colour)
	}
	if uploads {
		upload, err := HwSurfaceFilters(s.Publish.Codec(), s.Publish.Chroma)
		if err != nil {
			return nil, err
		}
		filters = append(filters, upload...)
	}

	args := []string{"-hide_banner", "-loglevel", "error"}
	args = append(args, device...)
	args = append(args, "-f", "lavfi", "-i", probeSource(width, height, s.Publish.Fps, heavy))
	args = append(args, "-frames:v", strconv.Itoa(frames))
	if len(filters) > 0 {
		args = append(args, "-vf", strings.Join(filters, ","))
	}
	args = append(args, enc...)
	if !uploads {
		args = append(args, "-pix_fmt", s.Publish.Chroma)
	}
	if s.Publish.Chroma != "gbrp" {
		args = append(args, "-color_range", s.Publish.ColorRange)
	}
	args = append(args, "-g", strconv.Itoa(gopFor(s)))
	return append(args, "-f", "null", "-"), nil
}

// BuildProbeCeilingArgs returns the same generated frames running into the null muxer
// with no encoder between, which times the lavfi source alone.
//
// It separates a measurement from its instrument.
// An encoder faster than the source can feed it reads as the source's rate,
// so an encode timed at the ceiling measured the generator.
func BuildProbeCeilingArgs(width, height, fps, frames int, heavy bool) []string {
	assert.Assert(width > 0 && height > 0, "a probe encodes frames of a resolved picture size", width, height)
	assert.Assert(frames > 0, "a probe encodes at least one frame", frames)
	assert.Assert(fps > 0, "a probe generates frames at a positive rate", fps)

	return []string{
		"-hide_banner", "-loglevel", "error",
		"-f", "lavfi", "-i", probeSource(width, height, fps, heavy),
		"-frames:v", strconv.Itoa(frames),
		"-f", "null", "-",
	}
}

func probeSource(width, height, fps int, heavy bool) string {
	source := probeLightSource
	if heavy {
		source = probeHeavySource
	}
	return fmt.Sprintf(source, width, height, fps)
}
