package ffmpeg

import (
	"fmt"
	"strconv"
	"strings"

	"bjoernblessin.de/go-utils/util/assert"

	"bjoernblessin.de/screenshare/capabilities"
	"bjoernblessin.de/screenshare/settings"
)

// probeHeavySource and probeLightSource are the lavfi graphs the two ends of the
// measured range are generated by, and the ffmpeg counterpart of the GStreamer
// engine's two test patterns: the same two kinds of content, so a machine's two
// engines are measured against the same question.
//
// The heavy one is uncorrelated noise, which nothing predicts from the frame before
// it and nothing repeats within a frame, so an encoder does the most work any
// content can ask of it. The light one is ffmpeg's own test picture, mostly flat
// fields with a moving element. A screen sits between them.
//
// The noise is generated over a solid colour rather than over a picture, so what the
// filter costs stays the same whatever the frame it is laid on holds.
const (
	probeHeavySource = "color=c=gray:s=%dx%d:r=%d,format=bgr0,noise=alls=100:allf=t+u"
	probeLightSource = "testsrc=size=%dx%d:rate=%d"
)

// BuildEncodeProbeArgs returns the ffmpeg arguments that encode generated frames
// with this stream's encoder and throw the coded bytes away, so the rate this
// machine sustains can be timed without a screen to capture or a relay to send to.
//
// The encoder half is what a publish run builds: the same encoder with the same
// rate-control arguments, the same pixel format, colour range and keyframe interval.
// The two ends are the difference: a lavfi source generates the frames a screen
// grabber would acquire, and the null muxer discards what a transport would send.
//
// heavy picks the end of the content range the frames are generated at
// (probeHeavySource, probeLightSource). frames is how many are encoded, and the
// caller times the run.
//
// A surface encoder still uploads, as it does for a run, since a VAAPI or QSV
// encoder reads GPU surfaces and measuring it any other way would measure nothing
// it does. What the probe cannot reproduce is the GPU capture path, where the
// frames are already on the device and never cross the bus: a generated frame
// starts in system memory, so that path is measured with the upload it avoids.
//
// The transport is not checked, unlike BuildPublishArgs. A probe measures what the
// machine does to frames, and refusing that measurement because the codec cannot
// reach the relay over the configured leg would answer a question about this CPU
// with a fact about a protocol.
func BuildEncodeProbeArgs(s settings.Stream, width, height, frames int, heavy bool) ([]string, error) {
	assert.Assert(width > 0 && height > 0, "a probe encodes frames of a resolved picture size", width, height)
	assert.Assert(frames > 0, "a probe encodes at least one frame", frames)

	if err := capabilities.Validate(capabilities.EngineFfmpeg, s.Codec, s.CapabilityOptions(), s.Cq, s.BitrateM); err != nil {
		return nil, err
	}
	if s.Fps <= 0 {
		return nil, fmt.Errorf("the ffmpeg publish engine needs a positive fps, got %d", s.Fps)
	}

	enc, err := encoderArgs(s, gopFor(s))
	if err != nil {
		return nil, err
	}
	assert.Assert(len(enc) > 0, "a validated stream yields an encoder", s.Codec)

	device, uploads, err := HwSurfaceDevice(s.Codec)
	if err != nil {
		return nil, err
	}

	var filters []string
	if colour := colourFilter(s.Chroma); colour != "" {
		filters = append(filters, colour)
	}
	if uploads {
		upload, err := HwSurfaceFilters(s.Codec, s.Chroma)
		if err != nil {
			return nil, err
		}
		filters = append(filters, upload...)
	}

	args := []string{"-hide_banner", "-loglevel", "error"}
	args = append(args, device...)
	args = append(args, "-f", "lavfi", "-i", probeSource(width, height, s.Fps, heavy))
	args = append(args, "-frames:v", strconv.Itoa(frames))
	if len(filters) > 0 {
		args = append(args, "-vf", strings.Join(filters, ","))
	}
	args = append(args, enc...)
	if !uploads {
		args = append(args, "-pix_fmt", s.Chroma)
	}
	if s.Chroma != "gbrp" {
		args = append(args, "-color_range", s.ColorRange)
	}
	args = append(args, "-g", strconv.Itoa(gopFor(s)))
	return append(args, "-f", "null", "-"), nil
}

// BuildProbeCeilingArgs returns the same generated frames running into the null
// muxer and nothing else, so the rate the lavfi source alone reaches can be timed.
//
// It is what tells a measurement apart from its own instrument. An encoder faster
// than the source can feed it is timed against the source rather than against
// itself, and the two readings together are what says so: a probe that lands at its
// ceiling measured the generator.
func BuildProbeCeilingArgs(width, height, fps, frames int, heavy bool) []string {
	assert.Assert(width > 0 && height > 0, "a probe encodes frames of a resolved picture size", width, height)
	assert.Assert(frames > 0, "a probe encodes at least one frame", frames)
	assert.Assert(fps > 0, "a probe generates frames at a positive rate", fps)

	return []string{
		"-hide_banner", "-loglevel", "error",
		"-f", "lavfi", "-i", probeSource(width, height, fps, heavy),
		"-frames:v", strconv.Itoa(frames),
		"-f", "null", "-",
	}
}

// probeSource renders the lavfi graph for one end of the content range.
func probeSource(width, height, fps int, heavy bool) string {
	source := probeLightSource
	if heavy {
		source = probeHeavySource
	}
	return fmt.Sprintf(source, width, height, fps)
}
