// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {relay} from '../models';
import {display} from '../models';
import {platform} from '../models';

export function GetSettings():Promise<settings.Stream>;

export function Live():Promise<relay.Status>;

export function MeasureUplink():Promise<number>;

export function Monitors():Promise<Array<display.Monitor>>;

export function OpenLog(arg1:string):Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function Platform():Promise<platform.Info>;

export function PublishCommand(arg1:settings.Stream):Promise<string>;

export function Publishing():Promise<boolean>;

export function SaveSettings(arg1:settings.Stream):Promise<void>;

export function StartPublish(arg1:settings.Stream):Promise<void>;

export function StartWatch(arg1:string):Promise<void>;

export function StopPublish():Promise<void>;

export function StopWatch(arg1:string):Promise<void>;

export function Transports():Promise<Array<string>>;

export function Watching():Promise<Array<string>>;
