// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Capabilities() {
  return window['go']['main']['App']['Capabilities']();
}

export function CaptureTransports() {
  return window['go']['main']['App']['CaptureTransports']();
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function Encoders() {
  return window['go']['main']['App']['Encoders']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GridViewerRunning() {
  return window['go']['main']['App']['GridViewerRunning']();
}

export function Live() {
  return window['go']['main']['App']['Live']();
}

export function MeasureUplink() {
  return window['go']['main']['App']['MeasureUplink']();
}

export function Monitors() {
  return window['go']['main']['App']['Monitors']();
}

export function OpenLog(arg1) {
  return window['go']['main']['App']['OpenLog'](arg1);
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function PublishCommand(arg1) {
  return window['go']['main']['App']['PublishCommand'](arg1);
}

export function Publishing() {
  return window['go']['main']['App']['Publishing']();
}

export function SavePreset(arg1, arg2) {
  return window['go']['main']['App']['SavePreset'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartGridViewer(arg1, arg2) {
  return window['go']['main']['App']['StartGridViewer'](arg1, arg2);
}

export function StartPublish(arg1) {
  return window['go']['main']['App']['StartPublish'](arg1);
}

export function StartTestStreams(arg1) {
  return window['go']['main']['App']['StartTestStreams'](arg1);
}

export function StartWall(arg1, arg2) {
  return window['go']['main']['App']['StartWall'](arg1, arg2);
}

export function StartWatch(arg1, arg2) {
  return window['go']['main']['App']['StartWatch'](arg1, arg2);
}

export function StopGridViewer() {
  return window['go']['main']['App']['StopGridViewer']();
}

export function StopPublish() {
  return window['go']['main']['App']['StopPublish']();
}

export function StopTestStreams() {
  return window['go']['main']['App']['StopTestStreams']();
}

export function StopWall() {
  return window['go']['main']['App']['StopWall']();
}

export function StopWatch(arg1, arg2) {
  return window['go']['main']['App']['StopWatch'](arg1, arg2);
}

export function TestStreamsRunning() {
  return window['go']['main']['App']['TestStreamsRunning']();
}

export function Transports() {
  return window['go']['main']['App']['Transports']();
}

export function WallRunning() {
  return window['go']['main']['App']['WallRunning']();
}

export function WatchTransports() {
  return window['go']['main']['App']['WatchTransports']();
}

export function Watching() {
  return window['go']['main']['App']['Watching']();
}
