// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AudioCodecs() {
  return window['go']['main']['App']['AudioCodecs']();
}

export function Capabilities() {
  return window['go']['main']['App']['Capabilities']();
}

export function CaptureEngines() {
  return window['go']['main']['App']['CaptureEngines']();
}

export function CaptureTransports() {
  return window['go']['main']['App']['CaptureTransports']();
}

export function Decoders() {
  return window['go']['main']['App']['Decoders']();
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function Encoders() {
  return window['go']['main']['App']['Encoders']();
}

export function ForgetPortalConsent() {
  return window['go']['main']['App']['ForgetPortalConsent']();
}

export function FrameMemories() {
  return window['go']['main']['App']['FrameMemories']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetPublishState() {
  return window['go']['main']['App']['GetPublishState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GpuPaths() {
  return window['go']['main']['App']['GpuPaths']();
}

export function GridTransports() {
  return window['go']['main']['App']['GridTransports']();
}

export function Live() {
  return window['go']['main']['App']['Live']();
}

export function MeasureEncodeRate(arg1) {
  return window['go']['main']['App']['MeasureEncodeRate'](arg1);
}

export function MeasureUplink() {
  return window['go']['main']['App']['MeasureUplink']();
}

export function Monitors() {
  return window['go']['main']['App']['Monitors']();
}

export function NativeGridRunning() {
  return window['go']['main']['App']['NativeGridRunning']();
}

export function NativeGridWatching() {
  return window['go']['main']['App']['NativeGridWatching']();
}

export function OpenLog(arg1) {
  return window['go']['main']['App']['OpenLog'](arg1);
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function PublishCommand(arg1) {
  return window['go']['main']['App']['PublishCommand'](arg1);
}

export function Publishing() {
  return window['go']['main']['App']['Publishing']();
}

export function Republish(arg1) {
  return window['go']['main']['App']['Republish'](arg1);
}

export function SavePreset(arg1, arg2) {
  return window['go']['main']['App']['SavePreset'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartNativeGrid() {
  return window['go']['main']['App']['StartNativeGrid']();
}

export function StartPublish(arg1) {
  return window['go']['main']['App']['StartPublish'](arg1);
}

export function StartTestStreams(arg1) {
  return window['go']['main']['App']['StartTestStreams'](arg1);
}

export function StartWatch(arg1, arg2) {
  return window['go']['main']['App']['StartWatch'](arg1, arg2);
}

export function StopNativeGrid() {
  return window['go']['main']['App']['StopNativeGrid']();
}

export function StopPublish() {
  return window['go']['main']['App']['StopPublish']();
}

export function StopTestStreams() {
  return window['go']['main']['App']['StopTestStreams']();
}

export function StopWatch(arg1, arg2) {
  return window['go']['main']['App']['StopWatch'](arg1, arg2);
}

export function StoreNotice() {
  return window['go']['main']['App']['StoreNotice']();
}

export function TestStreamsRunning() {
  return window['go']['main']['App']['TestStreamsRunning']();
}

export function TransportFormats() {
  return window['go']['main']['App']['TransportFormats']();
}

export function WatchTransports() {
  return window['go']['main']['App']['WatchTransports']();
}

export function WatchTransportsByFormat() {
  return window['go']['main']['App']['WatchTransportsByFormat']();
}

export function Watching() {
  return window['go']['main']['App']['Watching']();
}
