// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capabilities} from '../models';
import {encoders} from '../models';
import {settings} from '../models';
import {main} from '../models';
import {gpupath} from '../models';
import {relay} from '../models';
import {encoderate} from '../models';
import {display} from '../models';
import {platform} from '../models';

export function AudioCodecs():Promise<Array<capabilities.AudioCodec>>;

export function Capabilities():Promise<Array<capabilities.Codec>>;

export function CaptureEngines():Promise<Record<string, string>>;

export function CaptureTransports():Promise<Record<string, Array<string>>>;

export function Decoders():Promise<Array<capabilities.Decoder>>;

export function DeletePreset(arg1:string):Promise<void>;

export function Encoders():Promise<encoders.Availability>;

export function ForgetPortalConsent():Promise<void>;

export function FrameMemories():Promise<Array<string>>;

export function GetPresets():Promise<Array<settings.Preset>>;

export function GetPublishState():Promise<main.PublishStateEvent>;

export function GetSettings():Promise<settings.Stream>;

export function GpuPaths():Promise<Array<gpupath.Path>>;

export function GridTransports():Promise<Array<string>>;

export function Live():Promise<relay.Status>;

export function MeasureEncodeRate(arg1:settings.Stream):Promise<encoderate.Rate>;

export function MeasureUplink():Promise<number>;

export function Monitors():Promise<Array<display.Monitor>>;

export function NativeGridRunning():Promise<boolean>;

export function NativeGridWatching():Promise<Array<string>>;

export function OpenLog(arg1:string):Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function Platform():Promise<platform.Info>;

export function PublishCommand(arg1:settings.Stream):Promise<string>;

export function Publishing():Promise<boolean>;

export function Republish(arg1:settings.Stream):Promise<void>;

export function SavePreset(arg1:string,arg2:settings.Stream):Promise<void>;

export function SaveSettings(arg1:settings.Stream):Promise<void>;

export function StartNativeGrid():Promise<void>;

export function StartPublish(arg1:settings.Stream):Promise<void>;

export function StartTestStreams(arg1:number):Promise<void>;

export function StartWatch(arg1:string,arg2:string):Promise<void>;

export function StopNativeGrid():Promise<void>;

export function StopPublish():Promise<void>;

export function StopTestStreams():Promise<void>;

export function StopWatch(arg1:string,arg2:string):Promise<void>;

export function StoreNotice():Promise<string>;

export function TestStreamsRunning():Promise<number>;

export function TransportFormats():Promise<Array<main.TransportCarriage>>;

export function WatchTransports():Promise<Array<string>>;

export function WatchTransportsByFormat():Promise<Record<string, Array<string>>>;

export function Watching():Promise<Array<main.WatchKey>>;
