// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Capabilities() {
  return window['go']['main']['App']['Capabilities']();
}

export function Encoders() {
  return window['go']['main']['App']['Encoders']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Live() {
  return window['go']['main']['App']['Live']();
}

export function MeasureUplink() {
  return window['go']['main']['App']['MeasureUplink']();
}

export function Monitors() {
  return window['go']['main']['App']['Monitors']();
}

export function OpenLog(arg1) {
  return window['go']['main']['App']['OpenLog'](arg1);
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function PublishCommand(arg1) {
  return window['go']['main']['App']['PublishCommand'](arg1);
}

export function Publishing() {
  return window['go']['main']['App']['Publishing']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartPublish(arg1) {
  return window['go']['main']['App']['StartPublish'](arg1);
}

export function StartWatch(arg1) {
  return window['go']['main']['App']['StartWatch'](arg1);
}

export function StopPublish() {
  return window['go']['main']['App']['StopPublish']();
}

export function StopWatch(arg1) {
  return window['go']['main']['App']['StopWatch'](arg1);
}

export function Transports() {
  return window['go']['main']['App']['Transports']();
}

export function Watching() {
  return window['go']['main']['App']['Watching']();
}
